# Generated by Django 5.1.5 on 2025-01-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('java', models.IntegerField()),
                ('python', models.IntegerField()),
                ('dbms', models.IntegerField()),
                ('data_science', models.IntegerField()),
                ('aoa', models.IntegerField()),
                ('iks', models.IntegerField()),
            ],
        ),
    ]
